# Generated by Django 2.1.5 on 2019-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0003_player_ship_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='radius_x',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='radius_y',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
