# Generated by Django 2.1.5 on 2019-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0004_auto_20190220_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='offset',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
