# Generated by Django 2.1.5 on 2019-02-25 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0005_planet_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='offer_demand_time_event_move',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='offer_demand_time_event_time',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='planet_influence_track',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=4), default=([0, 0, 0, 0],), size=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='planet_rotation_event_move',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='planet_rotation_event_time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='next_move_type',
            field=models.CharField(blank=True, choices=[('s', 'Choose starting position'), ('m', 'Market action'), ('f', 'Fly to another planet')], default='s', help_text='What is the next move type', max_length=1),
        ),
    ]
