# Generated by Django 2.1.5 on 2019-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0006_auto_20190225_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
