# Generated by Django 2.1.5 on 2019-03-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0008_remove_game_next_move_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='offer_demand_time_event_move',
            new_name='offer_demand_event_move',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='offer_demand_time_event_time',
            new_name='offer_demand_event_time',
        ),
    ]
