# Generated by Django 2.1.5 on 2019-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0009_auto_20190307_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_passed',
            field=models.BooleanField(default=False),
        ),
    ]
