# Generated by Django 2.1.5 on 2019-03-19 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0010_player_has_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5),
        ),
    ]
