# Generated by Django 2.1.5 on 2019-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0013_auto_20190416_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='resource_limit',
            field=models.IntegerField(default=9),
        ),
    ]
