# Generated by Django 2.1.5 on 2019-06-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0015_auto_20190530_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='buy_resources',
            new_name='planet_demand_resources',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='cost_buy_resource',
            new_name='planet_demand_resources_price',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='sell_resources',
            new_name='planet_supply_resources',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='cost_sell_resource',
            new_name='planet_supply_resources_price',
        ),
    ]
