# Generated by Django 2.1.5 on 2019-06-12 18:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0016_auto_20190610_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='add_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='add_demand_event_move',
            field=models.IntegerField(default=-8),
        ),
        migrations.AddField(
            model_name='game',
            name='add_demand_event_time',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='planet',
            name='add_demand_resource',
            field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Resources the planet supplies', max_length=1),
        ),
        migrations.AddField(
            model_name='planet',
            name='add_demand_resource_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planet',
            name='add_demand_resource_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_demand_resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Resources the planet demands', max_length=1), size=5),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_supply_resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Resources the planet supplies', max_length=1), size=5),
        ),
    ]
