# Generated by Django 2.2.10 on 2020-04-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0018_game_finish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='add_demand',
        ),
        migrations.RemoveField(
            model_name='game',
            name='add_demand_event_move',
        ),
        migrations.RemoveField(
            model_name='game',
            name='add_demand_event_time',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='add_demand_resource',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='add_demand_resource_price',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='add_demand_resource_time',
        ),
    ]
