# Generated by Django 2.2.10 on 2020-05-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0019_auto_20200413_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='planet_demand_resources',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='planet_demand_resources_price',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='planet_supply_resources',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='planet_supply_resources_price',
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_demand_resource',
            field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Resource the planet demands', max_length=1),
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_demand_resource_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_supply_resource',
            field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Resource the planet supplies', max_length=1),
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_supply_resource_price',
            field=models.IntegerField(default=0),
        ),
    ]
