version: '3.7'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    #command: gunicorn doppeldenk.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    #expose:
    #  - 8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=doppeldenk

  #nginx:
  #  build: ./nginx
  #  ports:
  #    - 1337:80
  #  depends_on:
  #    - web

volumes:
  postgres_data: