# Generated by Django 2.1.5 on 2019-02-16 19:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('number_of_players', models.IntegerField()),
                ('next_move_number', models.IntegerField()),
                ('next_move_type', models.CharField(blank=True, choices=[('m', 'Market action'), ('f', 'Fly to another planet')], default='f', help_text='What is the next move type', max_length=1)),
                ('game_state', models.CharField(blank=True, choices=[('w', 'waiting'), ('r', 'running'), ('f', 'finished')], default='w', help_text='In which state is the game', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(default='#000000', max_length=50)),
                ('number_of_hexes', models.IntegerField()),
                ('position_of_hexes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2), size=20)),
                ('current_position', models.IntegerField()),
                ('buy_resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Kind of Resource to buy', max_length=1), size=5)),
                ('cost_buy_resource', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
                ('sell_resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Kind of Resource for sell', max_length=1), size=5)),
                ('cost_sell_resource', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Cargo of the player', max_length=1), size=9)),
                ('money', models.IntegerField()),
                ('ship_position', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('last_move', models.IntegerField()),
                ('time_spent', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='planets',
            field=models.ManyToManyField(to='spacetrading.Planet'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='spacetrading.Player'),
        ),
    ]
