# Generated by Django 2.1.2 on 2018-10-24 17:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spacetrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_players', models.IntegerField()),
                ('next_move_number', models.IntegerField()),
                ('next_move_type', models.CharField(blank=True, choices=[('m', 'Market action'), ('f', 'Fly to another planet')], default='f', help_text='What is the next move type', max_length=1)),
                ('game_state', models.CharField(blank=True, choices=[('w', 'waiting'), ('r', 'running'), ('f', 'finished')], default='w', help_text='In which state is the game', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_hexes', models.IntegerField()),
                ('current_position', models.IntegerField()),
                ('buy_resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Kind of Resource to buy', max_length=1), size=5)),
                ('cost_buy_resource', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
                ('sell_resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Kind of Resource for sell', max_length=1), size=5)),
                ('cost_sell_resource', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacetrading.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'no resource'), ('1', 'resource1'), ('2', 'resource2'), ('3', 'resource3'), ('4', 'resource4'), ('5', 'resource5')], default='0', help_text='Cargo of the player', max_length=1), size=9)),
                ('money', models.IntegerField()),
                ('last_move', models.IntegerField()),
                ('time_spent', models.IntegerField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacetrading.Game')),
                ('ship_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacetrading.Planet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SpaceTradingModel',
        ),
    ]
