# Generated by Django 2.1.5 on 2019-02-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='colour',
            field=models.CharField(default='white', max_length=100),
            preserve_default=False,
        ),
    ]
