# Generated by Django 2.1.5 on 2019-01-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0003_auto_20181027_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='planets',
            field=models.ManyToManyField(to='spacetrading.Planet'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='spacetrading.Player'),
        ),
    ]
