# Generated by Django 2.1.5 on 2019-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0004_auto_20190125_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
