# Generated by Django 2.1.5 on 2019-02-11 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0005_game_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='colour',
            field=models.CharField(default='#000000', max_length=50),
        ),
        migrations.AddField(
            model_name='planet',
            name='position_of_hexes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2), default=[], size=20),
        ),
    ]
