# Generated by Django 2.1.5 on 2019-02-11 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0006_auto_20190211_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='position_of_hexes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2), size=20),
        ),
    ]
