# Generated by Django 2.1.5 on 2019-03-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0007_player_player_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='next_move_type',
        ),
    ]
