# Generated by Django 2.1.5 on 2019-03-02 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrading', '0007_player_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='planet_influence_track',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=20),
        ),
    ]
